name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    # rod / chrome fails on ubuntu-24.04 with following error:
    #
    # Failed to initialize TestBrowserManager connect to browser failed: [launcher] Failed to get the debug url:
    # [0605/002446.197692:FATAL:zygote_host_impl_linux.cc(126)] No usable sandbox! Update your kernel or see
    # https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information
    # on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try
    # using --no-sandbox.
    #
    # https://github.com/go-rod/rod/issues/1070
    #
    # But it works with ubuntu-22.04
    runs-on: ubuntu-22.04

    env:
      TERN_CONFIG: postgresql/tern.conf
      TERN_MIGRATIONS: postgresql/migrations
      LISTEN_ADDRESS: "127.0.0.1:8080"
      LOG_FORMAT: console
      TEST_PGDATABASE: web_starter_app_test
      TEST_DATABASE_COUNT: 1
      APP_PGUSER: web_starter_app
      DATABASE_URL: "host=127.0.0.1 user=web_starter_app password=password sslmode=disable"

    steps:
      - name: Start and set up PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          pg_isready
          sudo -u postgres createuser -s runner
          createdb runner

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        # with:
        #   bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install tern
        run: curl -L https://github.com/jackc/tern/releases/download/v2.2.0/tern_2.2.0_linux_amd64.tar.gz > tern.tar.gz && tar -zxf tern.tar.gz -C /usr/local/bin/

      - name: Create application database user
        run: psql -d postgres -c "create user web_starter_app with password 'password'"

      - name: Copy tern.conf
        run: cp .github/workflows/ci/tern.conf postgresql/tern.conf

      - name: Install templ
        run: curl -L https://github.com/a-h/templ/releases/download/v0.2.707/templ_Linux_x86_64.tar.gz > templ.tar.gz && tar -zxf templ.tar.gz -C /usr/local/bin/

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          # limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true

      - name: Run tests
        run: rake test
